creating sign up component  and finish styling it
mhmdwSamir/to-do-web-client pull request #3
Opened 2021-08-08 19:48 UTC by mhmdwSamir

2021-08-08 20:03 UTC, a7md940 requested changes
Create new component `TodoPageCompoment` that will be for routing `{ path: '', component: TodoPageComponent }`
And contains `app-todo-task` and `app-todo-stats`

2021-08-08 20:03 UTC, ahmedradwan94 commented on src/app/app.component.html
>        <app-todo-task></app-todo-task>
The todo components should be in routing not hard coded in `app.component.html`.
This wil solve the issue of appearing todo form and signup in the same page

2021-08-08 20:03 UTC, ahmedradwan94 commented on src/app/components/sign-up/sign-up.component.scss
> +.sign-up-section{
Good job for writing css classes in `kabeb case`

2021-08-08 20:13 UTC, mhmdwSamir commented on src/app/app.component.html
>        <app-todo-task></app-todo-task>
ok ,
i will search for put both of them in one routing

2021-08-08 20:15 UTC, mhmdwSamir commented on src/app/app.component.html
>        <app-todo-task></app-todo-task>
i need more comment [ killing comments ] YA RADWAN

2021-08-10 09:36 UTC, a7md940 reviewed
I'll merge this code, and in the future tasks we will refactor a lot of it.

2021-08-10 09:36 UTC, ahmedradwan94 commented on src/app/app.component.html
> +      <app-todo-form></app-todo-form>
why you still render `app-todo-form` in the `app.component.html` file ? @mhmdwSamir

2021-08-10 09:36 UTC, ahmedradwan94 commented on src/app/app-routing.module.ts
> +  { path:  'taskStaste', component: TodoStatsComponent},
You should create new component as i said before `TodoPageComponent` and you can add new route like `{ path: '', component: ToDoPageComponent }` with empty string so it will be the home page.
in `todo-page.component.html` file you can add `<app-todo-stats></app-todo-stats> and <app-todo-tasks></app-todo-tasks>`.

2021-08-10 09:37 UTC, merged